<?php

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'Admin dashboard';
$string['admindashboard:view'] = 'View admin dashboard';
$string['admindashboard:editcourseschedulenotes'] = 'Edit course schedule sticky notes on the admin dashboard';
$string['settingsheading'] = 'Admin dashboard settings';

$string['groqapikey'] = 'Groq API key';
$string['groqapikey_desc'] = 'API key used by the Ask the Data assistant.';
$string['groqmodel'] = 'Groq model';
$string['groqmodel_desc'] = 'Model name for Ask the Data requests.';
$string['groqendpoint'] = 'Groq API endpoint';
$string['groqendpoint_desc'] = 'OpenAI-compatible Groq chat completions endpoint.';

$string['courseschedulenotes_pagetitle'] = 'Course schedule notes';
$string['courseschedulenotes_intro'] = 'Edit the sticky notes shown on the main admin dashboard (course cadence, intakes, and reminders). You can save up to {$a} notes.';
$string['courseschedulenotes_nocap'] = 'You can view the schedule below. Only users with the edit permission (typically site managers) can change these notes.';
$string['courseschedulenotes_backdash'] = 'Back to dashboard';
$string['courseschedulenotes_formtitle'] = 'Sticky note content';
$string['courseschedulenotes_formhelp'] = 'Plain text only; use line breaks for paragraphs. Colours are cosmetic on the dashboard. Rows with both title and body empty are skipped. One extra blank row appears so you can add another note (up to {$a} total).';
$string['courseschedulenotes_untitled'] = 'Untitled note';
$string['courseschedulenotes_maxreached'] = 'You are at the maximum of {$a} notes. Save, then remove or shorten an existing note to add a different one.';
$string['courseschedulenotes_notelabel'] = 'Note {$a}';
$string['courseschedulenotes_field_title'] = 'Title';
$string['courseschedulenotes_field_body'] = 'Body';
$string['courseschedulenotes_field_variant'] = 'Card colour';
$string['courseschedulenotes_variant_lemon'] = 'Lemon';
$string['courseschedulenotes_variant_mint'] = 'Mint';
$string['courseschedulenotes_variant_lavender'] = 'Lavender';
$string['courseschedulenotes_variant_peach'] = 'Peach';
$string['courseschedulenotes_preview'] = 'Live preview';
$string['courseschedulenotes_board_eyebrow'] = 'Course cadence';
$string['courseschedulenotes_board_title'] = 'Schedule at a glance';
$string['courseschedulenotes_board_edit'] = 'Edit notes';
$string['courseschedulenotes_board_toggle_hide'] = 'Hide schedule notes';
$string['courseschedulenotes_board_toggle_show'] = 'Show schedule notes';

$string['task_send_module_reports'] = 'Send module reports to teachers';
$string['task_refresh_at_risk_cache'] = 'Refresh at-risk participant cache';
$string['email_modulereport_title'] = 'Module Pass/Fail Report';
$string['email_modulereport_subject'] = 'Module report: {$a->course} - {$a->module}';

$string['privacy:export:atrisk'] = 'At-risk participant cache';
$string['privacy:metadata:groq'] = 'The plugin can send dashboard prompts and selected dashboard data to Groq when Groq-backed features are enabled.';
$string['privacy:metadata:groq:dashboarddata'] = 'Aggregated dashboard metrics and selected contextual data used to answer dashboard questions.';
$string['privacy:metadata:groq:feedbackcomments'] = 'Feedback comments submitted in Moodle activities when sentiment analysis is requested.';
$string['privacy:metadata:groq:prompt'] = 'The question or analysis prompt entered by the user or generated by the dashboard.';
$string['privacy:metadata:local_admindashboard_atrisk'] = 'Cached at-risk participant analytics used to render dashboard warning lists efficiently.';
$string['privacy:metadata:local_admindashboard_atrisk:completionpct'] = 'The participant completion percentage calculated for the course.';
$string['privacy:metadata:local_admindashboard_atrisk:courseid'] = 'The course associated with the cached analytics row.';
$string['privacy:metadata:local_admindashboard_atrisk:dayssincelogin'] = 'The number of days since the participant last accessed Moodle.';
$string['privacy:metadata:local_admindashboard_atrisk:deadlineat'] = 'The relevant course deadline timestamp used by the risk calculation.';
$string['privacy:metadata:local_admindashboard_atrisk:loginrisk'] = 'Whether the participant is considered at risk because of login activity.';
$string['privacy:metadata:local_admindashboard_atrisk:pacingrisk'] = 'Whether the participant is considered at risk because of course pacing.';
$string['privacy:metadata:local_admindashboard_atrisk:pretestavgpct'] = 'The comparison pre-test average percentage used by the risk calculation.';
$string['privacy:metadata:local_admindashboard_atrisk:pretestpct'] = 'The participant pre-test percentage used by the risk calculation.';
$string['privacy:metadata:local_admindashboard_atrisk:pretestrisk'] = 'Whether the participant is considered at risk because of pre-test performance.';
$string['privacy:metadata:local_admindashboard_atrisk:reasonsjson'] = 'JSON-encoded reasons explaining why the participant appears in the at-risk list.';
$string['privacy:metadata:local_admindashboard_atrisk:riskscore'] = 'The calculated at-risk score for the participant.';
$string['privacy:metadata:local_admindashboard_atrisk:timecreated'] = 'The time the cached analytics row was created.';
$string['privacy:metadata:local_admindashboard_atrisk:timemodified'] = 'The time the cached analytics row was last updated.';
$string['privacy:metadata:local_admindashboard_atrisk:userid'] = 'The participant represented by the cached analytics row.';
